# TiDB Cloud Connection Settings
spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/sys?useSSL=true&enabledTLSProtocols=TLSv1.2
spring.datasource.username=2hgFJYAh6aau8nD.root
spring.datasource.password=q9rRvpkMVOWyjIGL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
